[phases.setup]
nixPkgs = ["php82", "php82Extensions.mysqli", "php82Extensions.pdo_mysql", "php82Extensions.session"]

[phases.install]
cmds = ["mkdir -p /app"]

[start]
cmd = "php -c php.ini -S 0.0.0.0:$PORT"
